CREATE TYPE "BookingStatus" AS ENUM ('PENDING_PAYMENT', 'CONFIRMED', 'AWAITING_CONFIRMATION', 'COMPLETED', 'DISPUTED', 'CANCELLED', 'REFUNDED');

ALTER TABLE "Event" ADD COLUMN "isPaid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "price" INTEGER,
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'inr';

ALTER TABLE "Booking" ADD COLUMN "status" "BookingStatus" NOT NULL DEFAULT 'CONFIRMED',
ADD COLUMN "stripeSessionId" TEXT,
ADD COLUMN "stripePaymentIntentId" TEXT,
ADD COLUMN "amountPaid" INTEGER,
ADD COLUMN "currency" TEXT,
ADD COLUMN "paidAt" TIMESTAMP(3),
ADD COLUMN "disputedAt" TIMESTAMP(3),
ADD COLUMN "completedAt" TIMESTAMP(3);

ALTER TABLE "Booking" ALTER COLUMN "meetLink" DROP NOT NULL;
ALTER TABLE "Booking" ALTER COLUMN "googleEventId" DROP NOT NULL;

CREATE UNIQUE INDEX "Booking_stripeSessionId_key" ON "Booking"("stripeSessionId");
